### ISSUE TITLE
Documentation support

### ISSUE THREAD

**Issue by rikashore** [HannoZ/MerriamWebster.NET#10]
Is there a possibility for documentation in the near future? This seems to one of the only complete Wrappers for the Merriam-Webster API and it would be nice if we had some documentation, even simple XML Docstrings would do

**Comment by HannoZ** [comment]
Thanks for the feedback, I already added much of the avaible MW documentation to the corresponding response classes. But it turns out that I never enabled the XML doc generation.. That will be fixed in the next Nuget version. 
Can you tell me what other parts require additional documentation?

**Comment by rikashore** [comment]
Hi, thanks for reaching out, has 1.6 been pushed to nuget? I can't seem to find it

**Comment by HannoZ** [comment]
Sorry the build pipeline got stuck in queued status and besides that something went wrong with enabling XML documentation. But the package is now pushed to Nuget.
I will add some more XML documentation to the most important parts.

**Comment by rikashore** [comment]
Alright thank you, this might be too much to ask, but the examples in the readme aren't sufficient to show how one should handle results. Would it possible to perhaps, expand on the current example?

**Comment by HannoZ** [comment]
If you use the IEntryParser it should be rather straightforward how to handle the results, you get a model that contains the results of the call. The actual content is dependent on the API and search text, but for in-depth explanation of the results you should use the [documentation](https://www.dictionaryapi.com/products/json) of the MW API itself.

side note: I only have an API key for the Spanish-English dictionary API, so my only experience with the other APIs is from example output that I found in the documentation

**Comment by rikashore** [comment]
Alright, well thanks again!

**Comment by HannoZ** [comment]
A bunch of XML documentation has been added in the latest Nuget release
